server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true   # 추가

  kafka: # 추가
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


  elasticsearch:
    uris: ${ELASTIC_HOST}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

# Common Logging
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn